### ISSUE TITLE
The PrimeNumber function returns true when 1 (one) is send

### ISSUE THREAD

**Issue by DobleV55** [Aniket-Engg/solidity-school#31]
The number 1 (one) is not a prime number.

**Comment by Aniket-Engg** [comment]
@DobleV55  Thanks for raising this!!

**Comment by Aniket-Engg** [comment]
fixed by https://github.com/Aniket-Engg/solidity-school/commit/6df708fb3c03287ef67f86e7cb60f366a9c964e9
