### ISSUE TITLE
AttendanceRegisterExtended

### ISSUE THREAD

**Issue by Aniket-Engg** [Aniket-Engg/solidity-school#38]
Standard: 3
Sequence: 2
Contract Name: AttendanceRegisterExtended
Problem Statement: https://github.com/Aniket-Engg/solidity-school/tree/master/std-3/2_AttendanceRegisterExtended

Solve the problem statement.

Contribution guidelines: https://github.com/Aniket-Engg/solidity-school/wiki/Contribution-Guidelines

**Comment by RijuChakraborty** [comment]
Hi, I would like to work on this issue. Please assign this to me.

**Comment by Aniket-Engg** [comment]
Thanks @RijuChakraborty . It is assigned to you. Please have a look to contribution guidelines too.
