### ISSUE TITLE
childOrgEnrollment

### ISSUE THREAD

**Issue by Aniket-Engg** [Aniket-Engg/solidity-school#39]
Standard: 3
Sequence: 3
Contract Name: childOrgEnrollment
Problem Statement: https://github.com/Aniket-Engg/solidity-school/tree/master/std-3/3_childOrgEnrollment

Solve the problem statement.

Contribution guidelines: https://github.com/Aniket-Engg/solidity-school/wiki/Contribution-Guidelines

**Comment by Aniket-Engg** [comment]
Hello @mastershashank , You have been assigned. Please go through the contribution guidelines. In case you have any queries about problem statement, they can be raised here.

**Comment by mastershashank** [comment]
Thank you @Aniket-Engg I will start working on this issue.

**Comment by Aniket-Engg** [comment]
@mastershashank Have you made some progress?

**Comment by mastershashank** [comment]
@Aniket-Engg I am working on the Smart contract. facing some issues when I am implementing Inheritance. I need some assistance. How can I connect with you? This project is my first open-source contribution.

**Comment by mastershashank** [comment]
Sir, I need your assistance in completing the smart contract.

**Comment by Aniket-Engg** [comment]
Hello @mastershashank , you can read everything about inheritance here: https://docs.soliditylang.org/en/v0.8.17/contracts.html#inheritance

In case of any other query, you can put it here.
