### ISSUE TITLE
4_Onboarding

### ISSUE THREAD

**Issue by Aniket-Engg** [Aniket-Engg/solidity-school#50]
Standard: 3
Sequence: 4
Contract Name: childOrgEnrollment
Problem Statement: https://github.com/Aniket-Engg/solidity-school/tree/master/std-3/4_Onboarding

Solve the problem statement.

Contribution guidelines: https://github.com/Aniket-Engg/solidity-school/wiki/Contribution-Guidelines

**Comment by Aniket-Engg** [comment]
@amar-exe FYI

**Comment by amar-exe** [comment]
I will check it out when I have time, maybe this week or in the last week of April

**Comment by Aniket-Engg** [comment]
closed by #51
