### ISSUE TITLE
5_CalculatorUsingInterface

### ISSUE THREAD

**Issue by Aniket-Engg** [Aniket-Engg/solidity-school#53]
Standard: 3
Sequence: 5
Contract Name: CalculatorUsingInterface
Problem Statement: https://github.com/Aniket-Engg/solidity-school/tree/master/std-3/5_CalculatorUsingInterface

Solve the problem statement.

Contribution guidelines: https://github.com/Aniket-Engg/solidity-school/wiki/Contribution-Guidelines

**Comment by BrightTNut** [comment]
hi can i try this

**Comment by Aniket-Engg** [comment]
Yes sure @BrightTNut

**Comment by BrightTNut** [comment]
![Screenshot from 2023-06-22 01-08-39](https://github.com/Aniket-Engg/solidity-school/assets/118769123/0451f443-1e62-4f71-ac9f-5b883ceafd0a)

**Comment by Aniket-Engg** [comment]
@BrightTNut You don't need to update existing contract but to create a new contract as mentioned in the issue description. Also please check the guidelines for better understanding.
